name: Deploy Angular to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm install
        npm install -g @angular/cli
        
    - name: Install Angular Material
      run: |
        ng add @angular/material --defaults --skip-confirmation
        
    - name: Create missing template files
      run: |
        mkdir -p src/app/components/contact src/app/components/education
        touch src/app/components/contact/contact.component.html
        touch src/app/components/education/education.component.html
        
    - name: Build Angular app
      run: |
        ng build --configuration production --base-href="/aravind-portfolio/" --verbose
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/aravind-portfolio
